// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vstandup/vreport/Detail.html:1
package vreport

//line views/vstandup/vreport/Detail.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/standup"
	"github.com/kyleu/rituals/app/standup/report"
	"github.com/kyleu/rituals/app/user"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/components/view"
	"github.com/kyleu/rituals/views/layout"
)

//line views/vstandup/vreport/Detail.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vstandup/vreport/Detail.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vstandup/vreport/Detail.html:12
type Detail struct {
	layout.Basic
	Model              *report.Report
	StandupByStandupID *standup.Standup
	UserByUserID       *user.User
	Paths              []string
}

//line views/vstandup/vreport/Detail.html:20
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:20
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-report"><button type="button" title="JSON">`)
//line views/vstandup/vreport/Detail.html:23
	components.StreamSVGButton(qw422016, "code", ps)
//line views/vstandup/vreport/Detail.html:23
	qw422016.N().S(`</button></a>
      <a href="`)
//line views/vstandup/vreport/Detail.html:24
	qw422016.E().S(p.Model.WebPath(p.Paths...))
//line views/vstandup/vreport/Detail.html:24
	qw422016.N().S(`/edit" title="Edit"><button>`)
//line views/vstandup/vreport/Detail.html:24
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vstandup/vreport/Detail.html:24
	qw422016.N().S(`</button></a>
    </div>
    <h3>`)
//line views/vstandup/vreport/Detail.html:26
	components.StreamSVGIcon(qw422016, `file-alt`, ps)
//line views/vstandup/vreport/Detail.html:26
	qw422016.N().S(` `)
//line views/vstandup/vreport/Detail.html:26
	qw422016.E().S(p.Model.TitleString())
//line views/vstandup/vreport/Detail.html:26
	qw422016.N().S(`</h3>
    <div><a href="`)
//line views/vstandup/vreport/Detail.html:27
	qw422016.E().S(report.Route(p.Paths...))
//line views/vstandup/vreport/Detail.html:27
	qw422016.N().S(`"><em>Report</em></a></div>
    `)
//line views/vstandup/vreport/Detail.html:28
	StreamDetailTable(qw422016, p, ps)
//line views/vstandup/vreport/Detail.html:28
	qw422016.N().S(`
  </div>
`)
//line views/vstandup/vreport/Detail.html:31
	qw422016.N().S(`  `)
//line views/vstandup/vreport/Detail.html:32
	components.StreamJSONModal(qw422016, "report", "Report JSON", p.Model, 1)
//line views/vstandup/vreport/Detail.html:32
	qw422016.N().S(`
`)
//line views/vstandup/vreport/Detail.html:33
}

//line views/vstandup/vreport/Detail.html:33
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vstandup/vreport/Detail.html:33
	p.StreamBody(qw422016, as, ps)
//line views/vstandup/vreport/Detail.html:33
	qt422016.ReleaseWriter(qw422016)
//line views/vstandup/vreport/Detail.html:33
}

//line views/vstandup/vreport/Detail.html:33
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vstandup/vreport/Detail.html:33
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vstandup/vreport/Detail.html:33
	p.WriteBody(qb422016, as, ps)
//line views/vstandup/vreport/Detail.html:33
	qs422016 := string(qb422016.B)
//line views/vstandup/vreport/Detail.html:33
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vstandup/vreport/Detail.html:33
	return qs422016
//line views/vstandup/vreport/Detail.html:33
}

//line views/vstandup/vreport/Detail.html:35
func StreamDetailTable(qw422016 *qt422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:35
	qw422016.N().S(`
  <div class="mt overflow full-width">
    <table>
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:41
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vstandup/vreport/Detail.html:41
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Standup ID</th>
          <td class="nowrap">
            `)
//line views/vstandup/vreport/Detail.html:46
	if x := p.StandupByStandupID; x != nil {
//line views/vstandup/vreport/Detail.html:46
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:47
		qw422016.E().S(x.TitleString())
//line views/vstandup/vreport/Detail.html:47
		qw422016.N().S(` <a title="Standup" href="`)
//line views/vstandup/vreport/Detail.html:47
		qw422016.E().S(x.WebPath(p.Paths...))
//line views/vstandup/vreport/Detail.html:47
		qw422016.N().S(`">`)
//line views/vstandup/vreport/Detail.html:47
		components.StreamSVGLink(qw422016, `standup`, ps)
//line views/vstandup/vreport/Detail.html:47
		qw422016.N().S(`</a>
            `)
//line views/vstandup/vreport/Detail.html:48
	} else {
//line views/vstandup/vreport/Detail.html:48
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:49
		view.StreamUUID(qw422016, &p.Model.StandupID)
//line views/vstandup/vreport/Detail.html:49
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:50
	}
//line views/vstandup/vreport/Detail.html:50
	qw422016.N().S(`
          </td>
        </tr>
        <tr>
          <th class="shrink" title="Calendar date">Day</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:55
	view.StreamTimestampDay(qw422016, &p.Model.Day)
//line views/vstandup/vreport/Detail.html:55
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">User ID</th>
          <td class="nowrap">
            `)
//line views/vstandup/vreport/Detail.html:60
	if x := p.UserByUserID; x != nil {
//line views/vstandup/vreport/Detail.html:60
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:61
		qw422016.E().S(x.TitleString())
//line views/vstandup/vreport/Detail.html:61
		qw422016.N().S(` <a title="User" href="`)
//line views/vstandup/vreport/Detail.html:61
		qw422016.E().S(x.WebPath(p.Paths...))
//line views/vstandup/vreport/Detail.html:61
		qw422016.N().S(`">`)
//line views/vstandup/vreport/Detail.html:61
		components.StreamSVGLink(qw422016, `profile`, ps)
//line views/vstandup/vreport/Detail.html:61
		qw422016.N().S(`</a>
            `)
//line views/vstandup/vreport/Detail.html:62
	} else {
//line views/vstandup/vreport/Detail.html:62
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:63
		view.StreamUUID(qw422016, &p.Model.UserID)
//line views/vstandup/vreport/Detail.html:63
		qw422016.N().S(`
            `)
//line views/vstandup/vreport/Detail.html:64
	}
//line views/vstandup/vreport/Detail.html:64
	qw422016.N().S(`
          </td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Content</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:69
	view.StreamString(qw422016, p.Model.Content)
//line views/vstandup/vreport/Detail.html:69
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="HTML code, in string form">HTML</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:73
	view.StreamFormatLang(qw422016, p.Model.HTML, "html")
//line views/vstandup/vreport/Detail.html:73
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:77
	view.StreamTimestamp(qw422016, &p.Model.Created)
//line views/vstandup/vreport/Detail.html:77
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Updated</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:81
	view.StreamTimestamp(qw422016, p.Model.Updated)
//line views/vstandup/vreport/Detail.html:81
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vstandup/vreport/Detail.html:86
}

//line views/vstandup/vreport/Detail.html:86
func WriteDetailTable(qq422016 qtio422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vstandup/vreport/Detail.html:86
	StreamDetailTable(qw422016, p, ps)
//line views/vstandup/vreport/Detail.html:86
	qt422016.ReleaseWriter(qw422016)
//line views/vstandup/vreport/Detail.html:86
}

//line views/vstandup/vreport/Detail.html:86
func DetailTable(p *Detail, ps *cutil.PageState) string {
//line views/vstandup/vreport/Detail.html:86
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vstandup/vreport/Detail.html:86
	WriteDetailTable(qb422016, p, ps)
//line views/vstandup/vreport/Detail.html:86
	qs422016 := string(qb422016.B)
//line views/vstandup/vreport/Detail.html:86
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vstandup/vreport/Detail.html:86
	return qs422016
//line views/vstandup/vreport/Detail.html:86
}
