// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vstandup/vreport/Detail.html:2
package vreport

//line views/vstandup/vreport/Detail.html:2
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/standup"
	"github.com/kyleu/rituals/app/standup/report"
	"github.com/kyleu/rituals/app/user"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
)

//line views/vstandup/vreport/Detail.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vstandup/vreport/Detail.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vstandup/vreport/Detail.html:12
type Detail struct {
	layout.Basic
	Model              *report.Report
	StandupByStandupID *standup.Standup
	UserByUserID       *user.User
}

//line views/vstandup/vreport/Detail.html:19
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:19
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-report"><button type="button">JSON</button></a>
      <a href="`)
//line views/vstandup/vreport/Detail.html:23
	qw422016.E().S(p.Model.WebPath())
//line views/vstandup/vreport/Detail.html:23
	qw422016.N().S(`/edit"><button>`)
//line views/vstandup/vreport/Detail.html:23
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vstandup/vreport/Detail.html:23
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vstandup/vreport/Detail.html:25
	components.StreamSVGRefIcon(qw422016, `file-alt`, ps)
//line views/vstandup/vreport/Detail.html:25
	qw422016.N().S(` `)
//line views/vstandup/vreport/Detail.html:25
	qw422016.E().S(p.Model.TitleString())
//line views/vstandup/vreport/Detail.html:25
	qw422016.N().S(`</h3>
    <div><a href="/admin/db/standup/report"><em>Report</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:31
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vstandup/vreport/Detail.html:31
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Standup ID</th>
          <td class="nowrap">
            `)
//line views/vstandup/vreport/Detail.html:36
	components.StreamDisplayUUID(qw422016, &p.Model.StandupID)
//line views/vstandup/vreport/Detail.html:36
	if p.StandupByStandupID != nil {
//line views/vstandup/vreport/Detail.html:36
		qw422016.N().S(` (`)
//line views/vstandup/vreport/Detail.html:36
		qw422016.E().S(p.StandupByStandupID.TitleString())
//line views/vstandup/vreport/Detail.html:36
		qw422016.N().S(`)`)
//line views/vstandup/vreport/Detail.html:36
	}
//line views/vstandup/vreport/Detail.html:36
	qw422016.N().S(`
            <a title="Standup" href="`)
//line views/vstandup/vreport/Detail.html:37
	qw422016.E().S(`/admin/db/standup` + `/` + p.Model.StandupID.String())
//line views/vstandup/vreport/Detail.html:37
	qw422016.N().S(`">`)
//line views/vstandup/vreport/Detail.html:37
	components.StreamSVGRef(qw422016, "standup", 18, 18, "", ps)
//line views/vstandup/vreport/Detail.html:37
	qw422016.N().S(`</a>
          </td>
        </tr>
        <tr>
          <th class="shrink" title="Calendar date">Day</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:42
	components.StreamDisplayTimestampDay(qw422016, &p.Model.Day)
//line views/vstandup/vreport/Detail.html:42
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">User ID</th>
          <td class="nowrap">
            `)
//line views/vstandup/vreport/Detail.html:47
	components.StreamDisplayUUID(qw422016, &p.Model.UserID)
//line views/vstandup/vreport/Detail.html:47
	if p.UserByUserID != nil {
//line views/vstandup/vreport/Detail.html:47
		qw422016.N().S(` (`)
//line views/vstandup/vreport/Detail.html:47
		qw422016.E().S(p.UserByUserID.TitleString())
//line views/vstandup/vreport/Detail.html:47
		qw422016.N().S(`)`)
//line views/vstandup/vreport/Detail.html:47
	}
//line views/vstandup/vreport/Detail.html:47
	qw422016.N().S(`
            <a title="User" href="`)
//line views/vstandup/vreport/Detail.html:48
	qw422016.E().S(`/admin/db/user` + `/` + p.Model.UserID.String())
//line views/vstandup/vreport/Detail.html:48
	qw422016.N().S(`">`)
//line views/vstandup/vreport/Detail.html:48
	components.StreamSVGRef(qw422016, "profile", 18, 18, "", ps)
//line views/vstandup/vreport/Detail.html:48
	qw422016.N().S(`</a>
          </td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Content</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:53
	qw422016.E().S(p.Model.Content)
//line views/vstandup/vreport/Detail.html:53
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">HTML</th>
          <td><pre>`)
//line views/vstandup/vreport/Detail.html:57
	qw422016.E().S(p.Model.HTML)
//line views/vstandup/vreport/Detail.html:57
	qw422016.N().S(`</pre></td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:61
	components.StreamDisplayTimestamp(qw422016, &p.Model.Created)
//line views/vstandup/vreport/Detail.html:61
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Updated</th>
          <td>`)
//line views/vstandup/vreport/Detail.html:65
	components.StreamDisplayTimestamp(qw422016, p.Model.Updated)
//line views/vstandup/vreport/Detail.html:65
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vstandup/vreport/Detail.html:71
	qw422016.N().S(`  `)
//line views/vstandup/vreport/Detail.html:72
	components.StreamJSONModal(qw422016, "report", "Report JSON", p.Model, 1)
//line views/vstandup/vreport/Detail.html:72
	qw422016.N().S(`
`)
//line views/vstandup/vreport/Detail.html:73
}

//line views/vstandup/vreport/Detail.html:73
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/vreport/Detail.html:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vstandup/vreport/Detail.html:73
	p.StreamBody(qw422016, as, ps)
//line views/vstandup/vreport/Detail.html:73
	qt422016.ReleaseWriter(qw422016)
//line views/vstandup/vreport/Detail.html:73
}

//line views/vstandup/vreport/Detail.html:73
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vstandup/vreport/Detail.html:73
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vstandup/vreport/Detail.html:73
	p.WriteBody(qb422016, as, ps)
//line views/vstandup/vreport/Detail.html:73
	qs422016 := string(qb422016.B)
//line views/vstandup/vreport/Detail.html:73
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vstandup/vreport/Detail.html:73
	return qs422016
//line views/vstandup/vreport/Detail.html:73
}
