// Code generated by qtc from "Home.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/Home.html:1
package views

//line views/Home.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/estimate"
	"github.com/kyleu/rituals/app/retro"
	"github.com/kyleu/rituals/app/sprint"
	"github.com/kyleu/rituals/app/standup"
	"github.com/kyleu/rituals/app/team"
	"github.com/kyleu/rituals/app/util"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
	"github.com/kyleu/rituals/views/vworkspace/vwestimate"
	"github.com/kyleu/rituals/views/vworkspace/vwretro"
	"github.com/kyleu/rituals/views/vworkspace/vwsprint"
	"github.com/kyleu/rituals/views/vworkspace/vwstandup"
	"github.com/kyleu/rituals/views/vworkspace/vwteam"
)

//line views/Home.html:19
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/Home.html:19
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/Home.html:19
type Home struct {
	layout.Basic
	Teams     team.Teams
	Sprints   sprint.Sprints
	Estimates estimate.Estimates
	Standups  standup.Standups
	Retros    retro.Retros
}

//line views/Home.html:28
func (p *Home) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Home.html:28
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/Home.html:30
	components.StreamSVGRefIcon(qw422016, `app`, ps)
//line views/Home.html:30
	qw422016.E().S(util.AppName)
//line views/Home.html:30
	qw422016.N().S(`</h3>
    <p>Work with your team to estimate work, track your progress, and gather feedback</p>
    <p>
      This application allows you to collaborate with your team to manage your work.
      It provides teams, sprints, estimate sessions, standup meetings, and retrospectives.
    </p>
    <p>
      Source code available at <a href="https://github.com/kyleu/rituals.dev">https://github.com/kyleu/rituals.dev</a>.
    </p>
    <p>
      <a href="https://rituals.dev">rituals.dev</a> was built with help from <a href="https://projectforge.dev">Project Forge</a>.
    </p>
    <p>
      Get started below!
    </p>
  </div>
  `)
//line views/Home.html:46
	vwteam.StreamTeamListTable(qw422016, p.Teams, false, nil, nil, ps)
//line views/Home.html:46
	qw422016.N().S(`
  `)
//line views/Home.html:47
	vwsprint.StreamSprintListTable(qw422016, p.Sprints, nil, false, nil, nil, ps)
//line views/Home.html:47
	qw422016.N().S(`
  `)
//line views/Home.html:48
	vwestimate.StreamEstimateListTable(qw422016, p.Estimates, nil, nil, false, nil, nil, ps)
//line views/Home.html:48
	qw422016.N().S(`
  `)
//line views/Home.html:49
	vwstandup.StreamStandupListTable(qw422016, p.Standups, nil, nil, false, nil, nil, ps)
//line views/Home.html:49
	qw422016.N().S(`
  `)
//line views/Home.html:50
	vwretro.StreamRetroListTable(qw422016, p.Retros, nil, nil, false, nil, nil, ps)
//line views/Home.html:50
	qw422016.N().S(`
`)
//line views/Home.html:51
}

//line views/Home.html:51
func (p *Home) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/Home.html:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/Home.html:51
	p.StreamBody(qw422016, as, ps)
//line views/Home.html:51
	qt422016.ReleaseWriter(qw422016)
//line views/Home.html:51
}

//line views/Home.html:51
func (p *Home) Body(as *app.State, ps *cutil.PageState) string {
//line views/Home.html:51
	qb422016 := qt422016.AcquireByteBuffer()
//line views/Home.html:51
	p.WriteBody(qb422016, as, ps)
//line views/Home.html:51
	qs422016 := string(qb422016.B)
//line views/Home.html:51
	qt422016.ReleaseByteBuffer(qb422016)
//line views/Home.html:51
	return qs422016
//line views/Home.html:51
}
