// Code generated by qtc from "standup_permission.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/ddl/standup_permission.sql:1
package ddl

//line queries/ddl/standup_permission.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/standup_permission.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/standup_permission.sql:1
func StreamStandupPermissionDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/standup_permission.sql:1
	qw422016.N().S(`
drop table if exists "standup_permission";
-- `)
//line queries/ddl/standup_permission.sql:3
}

//line queries/ddl/standup_permission.sql:3
func WriteStandupPermissionDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/standup_permission.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/standup_permission.sql:3
	StreamStandupPermissionDrop(qw422016)
//line queries/ddl/standup_permission.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/standup_permission.sql:3
}

//line queries/ddl/standup_permission.sql:3
func StandupPermissionDrop() string {
//line queries/ddl/standup_permission.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/standup_permission.sql:3
	WriteStandupPermissionDrop(qb422016)
//line queries/ddl/standup_permission.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/standup_permission.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/standup_permission.sql:3
	return qs422016
//line queries/ddl/standup_permission.sql:3
}

// --

//line queries/ddl/standup_permission.sql:5
func StreamStandupPermissionCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/standup_permission.sql:5
	qw422016.N().S(`
create table if not exists "standup_permission" (
  "standup_id" uuid not null,
  "key" text not null,
  "value" text not null,
  "access" text not null,
  "created" timestamp not null default now(),
  foreign key ("standup_id") references "standup" ("id"),
  primary key ("standup_id", "key", "value")
);

create index if not exists "standup_permission__standup_id_idx" on "standup_permission" ("standup_id");

create index if not exists "standup_permission__key_idx" on "standup_permission" ("key");

create index if not exists "standup_permission__value_idx" on "standup_permission" ("value");
-- `)
//line queries/ddl/standup_permission.sql:21
}

//line queries/ddl/standup_permission.sql:21
func WriteStandupPermissionCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/standup_permission.sql:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/standup_permission.sql:21
	StreamStandupPermissionCreate(qw422016)
//line queries/ddl/standup_permission.sql:21
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/standup_permission.sql:21
}

//line queries/ddl/standup_permission.sql:21
func StandupPermissionCreate() string {
//line queries/ddl/standup_permission.sql:21
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/standup_permission.sql:21
	WriteStandupPermissionCreate(qb422016)
//line queries/ddl/standup_permission.sql:21
	qs422016 := string(qb422016.B)
//line queries/ddl/standup_permission.sql:21
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/standup_permission.sql:21
	return qs422016
//line queries/ddl/standup_permission.sql:21
}
