// Code generated by qtc from "EstimateWorkspace.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkspace/vwestimate/EstimateWorkspace.html:1
package vwestimate

//line views/vworkspace/vwestimate/EstimateWorkspace.html:1
import (
	"github.com/google/uuid"

	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/action"
	"github.com/kyleu/rituals/app/comment"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/enum"
	"github.com/kyleu/rituals/app/estimate"
	"github.com/kyleu/rituals/app/sprint"
	"github.com/kyleu/rituals/app/team"
	"github.com/kyleu/rituals/app/util"
	"github.com/kyleu/rituals/app/workspace"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
	"github.com/kyleu/rituals/views/vworkspace/vwutil"
)

//line views/vworkspace/vwestimate/EstimateWorkspace.html:19
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkspace/vwestimate/EstimateWorkspace.html:19
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkspace/vwestimate/EstimateWorkspace.html:19
type EstimateWorkspace struct {
	layout.Basic
	FullEstimate *workspace.FullEstimate
	Teams        team.Teams
	Sprints      sprint.Sprints
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:26
func (p *EstimateWorkspace) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:26
	qw422016.N().S(`
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:28
	w := p.FullEstimate
	e := w.Estimate
	self, others, _ := w.UtilMembers.Split(ps.Profile.ID)

//line views/vworkspace/vwestimate/EstimateWorkspace.html:31
	qw422016.N().S(`  <div class="flex-wrap">
    <div id="panel-summary">
      <div class="card">
        <div class="right">
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:36
	vwutil.StreamPermissionsLink(qw422016, enum.ModelServiceEstimate, e.ID, w.Permissions.ToPermissions(), ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:36
	qw422016.N().S(`
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:37
	vwutil.StreamComments(qw422016, enum.ModelServiceEstimate, e.ID, e.TitleString(), w.Comments, w.UtilMembers, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:37
	qw422016.N().S(`
        </div>
        <h3><a href="#modal-estimate-config" id="modal-estimate-config-link">
          <span id="model-icon">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:40
	components.StreamSVGRefIcon(qw422016, e.IconSafe(), ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:40
	qw422016.N().S(`</span>
          <span id="model-title">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:41
	qw422016.E().S(e.TitleString())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:41
	qw422016.N().S(`</span>
        </a></h3>
        `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:43
	vwutil.StreamBanner(qw422016, w.Team, w.Sprint, util.KeyEstimate)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:43
	qw422016.N().S(`
        `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:44
	StreamEstimateWorkspaceModal(qw422016, e, p.Teams, p.Sprints, w.Permissions.ToPermissions(), ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:44
	qw422016.N().S(`
      </div>
    </div>
    <div id="panel-detail">
      <div class="card">
        <div class="right"><a class="add-story-link" href="#modal-story--add"><button>Add Story</button></a></div>
        <h3><a class="add-story-link" href="#modal-story--add">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:50
	components.StreamSVGRefIcon(qw422016, util.KeyStory, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:50
	qw422016.N().S(`Stories</a></h3>
        `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:51
	StreamEstimateWorkspaceStories(qw422016, w, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:51
	qw422016.N().S(`
        `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:52
	StreamEstimateWorkspaceStoryModalAdd(qw422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:52
	qw422016.N().S(`
        `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:53
	StreamEstimateWorkspaceStoryModalEmpty(qw422016, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:53
	qw422016.N().S(`
      </div>
    </div>
    <div id="panel-self">
      <div class="card">
        <span id="self-id" style="display: none;">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:58
	qw422016.E().S(self.UserID.String())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:58
	qw422016.N().S(`</span>
        <h3><a href="#modal-self">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:59
	components.StreamSVGRefIcon(qw422016, `profile`, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:59
	qw422016.N().S(`<span id="self-name">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:59
	qw422016.E().S(self.Name)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:59
	qw422016.N().S(`</span></a></h3>
        <em id="self-role">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:60
	qw422016.E().S(string(self.Role))
//line views/vworkspace/vwestimate/EstimateWorkspace.html:60
	qw422016.N().S(`</em>
      </div>
      `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:62
	vwutil.StreamSelfModal(qw422016, self.Name, self.Picture, self.Role, e.PublicWebPath())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:62
	qw422016.N().S(`
    </div>
    <div id="panel-members">
      <div class="card">
        <h3><a href="#modal-invite">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:66
	components.StreamSVGRefIcon(qw422016, `users`, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:66
	qw422016.N().S(`Members</a></h3>
        <table class="mt expanded">
          <tbody>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:69
	for _, m := range others {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:69
		qw422016.N().S(`            `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:70
		vwutil.StreamMemberRow(qw422016, m, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:70
		qw422016.N().S(`
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:71
	}
//line views/vworkspace/vwestimate/EstimateWorkspace.html:71
	qw422016.N().S(`          </tbody>
        </table>
        <div id="member-modals">
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:75
	for _, m := range others {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:75
		qw422016.N().S(`          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:76
		vwutil.StreamMemberModal(qw422016, m, e.PublicWebPath())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:76
		qw422016.N().S(`
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:77
	}
//line views/vworkspace/vwestimate/EstimateWorkspace.html:77
	qw422016.N().S(`        </div>
      </div>
    </div>
    `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:81
	vwutil.StreamInviteModal(qw422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:81
	qw422016.N().S(`
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      initWorkspace("`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:85
	qw422016.E().S(util.KeyEstimate)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:85
	qw422016.N().S(`", "`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:85
	qw422016.E().S(e.ID.String())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:85
	qw422016.N().S(`");
    });
  </script>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
func (p *EstimateWorkspace) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	p.StreamBody(qw422016, as, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
func (p *EstimateWorkspace) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	p.WriteBody(qb422016, as, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	qs422016 := string(qb422016.B)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
	return qs422016
//line views/vworkspace/vwestimate/EstimateWorkspace.html:88
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:90
func StreamEstimateWorkspaceModal(qw422016 *qt422016.Writer, e *estimate.Estimate, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:90
	qw422016.N().S(`
  <div id="modal-estimate-config" class="modal" style="display: none;">
    <a class="backdrop" href="#"></a>
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="modal-close">×</a>
        <h2>Estimate</h2>
      </div>
      <div class="modal-body">
        <form action="`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:99
	qw422016.E().S(e.PublicWebPath())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:99
	qw422016.N().S(`" method="post" class="expanded">
          <input type="hidden" name="action" value="`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:100
	qw422016.E().S(string(action.ActUpdate))
//line views/vworkspace/vwestimate/EstimateWorkspace.html:100
	qw422016.N().S(`" />
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:101
	components.StreamFormVerticalInput(qw422016, "title", "", "Title", e.TitleString(), 5, "The name of your estimate")
//line views/vworkspace/vwestimate/EstimateWorkspace.html:101
	qw422016.N().S(`
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:102
	components.StreamFormVerticalIconPicker(qw422016, "icon", "Icon", e.IconSafe(), ps, 5)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:102
	qw422016.N().S(`
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:103
	components.StreamFormVerticalInputTags(qw422016, "choices", "", "Choices", e.Choices, ps, 5, "The available options for stories in this estimate")
//line views/vworkspace/vwestimate/EstimateWorkspace.html:103
	qw422016.N().S(`
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:104
	components.StreamFormVerticalSelect(qw422016, util.KeyTeam, "config-team-input", "Team", util.UUIDString(e.TeamID), teams.IDStrings(true), teams.TitleStrings("- no team -"), 5)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:104
	qw422016.N().S(`
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:105
	components.StreamFormVerticalSelect(qw422016, util.KeySprint, "config-sprint-input", "Sprint", util.UUIDString(e.SprintID), sprints.IDStrings(true), sprints.TitleStrings("- no sprint -"), 5)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:105
	qw422016.N().S(`
          <hr />
          `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:107
	vwutil.StreamPermissionsForm(qw422016, util.KeyEstimate, perms, true, teams, true, sprints, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:107
	qw422016.N().S(`
          <hr />
          <div class="right"><button type="submit">Save</button></div>
          <div class="clear"></div>
        </form>
      </div>
    </div>
  </div>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
func WriteEstimateWorkspaceModal(qq422016 qtio422016.Writer, e *estimate.Estimate, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	StreamEstimateWorkspaceModal(qw422016, e, teams, sprints, perms, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
func EstimateWorkspaceModal(e *estimate.Estimate, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) string {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	WriteEstimateWorkspaceModal(qb422016, e, teams, sprints, perms, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	qs422016 := string(qb422016.B)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
	return qs422016
//line views/vworkspace/vwestimate/EstimateWorkspace.html:115
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:117
func StreamEstimateWorkspaceList(qw422016 *qt422016.Writer, estimates estimate.Estimates, teamID *uuid.UUID, sprintID *uuid.UUID, showComments bool, comments comment.Comments, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:117
	qw422016.N().S(`
  <div class="card">
    <div class="right">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:119
	vwutil.StreamEditWorkspaceForm(qw422016, util.KeyEstimate, teamID, sprintID, "New Estimate")
//line views/vworkspace/vwestimate/EstimateWorkspace.html:119
	qw422016.N().S(`</div>
    <h3 title="Planning poker for any stories you need to work on">`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:120
	components.StreamSVGRefIcon(qw422016, util.KeyEstimate, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:120
	qw422016.N().S(`Estimates</h3>
    <table id="estimate-list" class="mt expanded">
      <tbody>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:123
	if len(estimates) == 0 {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:123
		qw422016.N().S(`          <tr class="empty"><td><em>no estimates</em></td></tr>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:125
	} else {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:126
		for _, x := range estimates {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:126
			qw422016.N().S(`          <tr id="estimate-list-`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:127
			qw422016.E().S(x.ID.String())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:127
			qw422016.N().S(`">
            <td>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:129
			if showComments {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:129
				qw422016.N().S(`              <div class="right">
                `)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:131
				vwutil.StreamComments(qw422016, enum.ModelServiceEstimate, x.ID, x.TitleString(), comments, nil, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:131
				qw422016.N().S(`
              </div>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:133
			}
//line views/vworkspace/vwestimate/EstimateWorkspace.html:133
			qw422016.N().S(`              <a href="`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:134
			qw422016.E().S(x.PublicWebPath())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:134
			qw422016.N().S(`"><div>
                <span>`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:135
			components.StreamSVGRef(qw422016, x.IconSafe(), 16, 16, "icon", ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:135
			qw422016.N().S(`</span><span>`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:135
			qw422016.E().S(x.TitleString())
//line views/vworkspace/vwestimate/EstimateWorkspace.html:135
			qw422016.N().S(`</span>
              </div></a>
            </td>
          </tr>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:139
		}
//line views/vworkspace/vwestimate/EstimateWorkspace.html:140
	}
//line views/vworkspace/vwestimate/EstimateWorkspace.html:140
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
func WriteEstimateWorkspaceList(qq422016 qtio422016.Writer, estimates estimate.Estimates, teamID *uuid.UUID, sprintID *uuid.UUID, showComments bool, comments comment.Comments, ps *cutil.PageState) {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	StreamEstimateWorkspaceList(qw422016, estimates, teamID, sprintID, showComments, comments, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
}

//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
func EstimateWorkspaceList(estimates estimate.Estimates, teamID *uuid.UUID, sprintID *uuid.UUID, showComments bool, comments comment.Comments, ps *cutil.PageState) string {
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	WriteEstimateWorkspaceList(qb422016, estimates, teamID, sprintID, showComments, comments, ps)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	qs422016 := string(qb422016.B)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
	return qs422016
//line views/vworkspace/vwestimate/EstimateWorkspace.html:144
}
