// Code generated by qtc from "EstimateWorkspace.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkspace/EstimateWorkspace.html:1
package vworkspace

//line views/vworkspace/EstimateWorkspace.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/util"
	"github.com/kyleu/rituals/app/workspace"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
)

//line views/vworkspace/EstimateWorkspace.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkspace/EstimateWorkspace.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkspace/EstimateWorkspace.html:10
type EstimateWorkspace struct {
	layout.Basic
	Estimate *workspace.FullEstimate
}

//line views/vworkspace/EstimateWorkspace.html:15
func (p *EstimateWorkspace) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/EstimateWorkspace.html:15
	qw422016.N().S(`
`)
//line views/vworkspace/EstimateWorkspace.html:16
	w := p.Estimate

//line views/vworkspace/EstimateWorkspace.html:17
	t := w.Estimate

//line views/vworkspace/EstimateWorkspace.html:19
	self, others, err := w.Members.Split(ps.Profile.ID)
	if err != nil {
		panic(err)
	}

//line views/vworkspace/EstimateWorkspace.html:23
	qw422016.N().S(`  <div style="display: flex; flex-wrap: wrap;">
    <div id="panel-summary">
      <div class="card">
        <div class="right"><a href="#modal-estimate"><button type="button">JSON</button></a></div>
        <a href="#modal-estimate-config"><h3>`)
//line views/vworkspace/EstimateWorkspace.html:28
	components.StreamSVGRefIcon(qw422016, `estimate`, ps)
//line views/vworkspace/EstimateWorkspace.html:28
	qw422016.E().S(t.TitleString())
//line views/vworkspace/EstimateWorkspace.html:28
	qw422016.N().S(`</h3></a>
        `)
//line views/vworkspace/EstimateWorkspace.html:29
	StreamBanner(qw422016, w.Team, w.Sprint, "estimate")
//line views/vworkspace/EstimateWorkspace.html:29
	qw422016.N().S(`
        `)
//line views/vworkspace/EstimateWorkspace.html:30
	StreamEstimateWorkspaceModal(qw422016, w)
//line views/vworkspace/EstimateWorkspace.html:30
	qw422016.N().S(`
      </div>
    </div>
    <div id="panel-detail">
      <div class="card">
        <h3>`)
//line views/vworkspace/EstimateWorkspace.html:35
	components.StreamSVGRefIcon(qw422016, `book-reader`, ps)
//line views/vworkspace/EstimateWorkspace.html:35
	qw422016.N().S(`Stories</h3>
        <table class="mt expanded">
          <tbody>
`)
//line views/vworkspace/EstimateWorkspace.html:38
	for _, s := range w.Stories {
//line views/vworkspace/EstimateWorkspace.html:38
		qw422016.N().S(`            <tr>
              <td><a href="#modal-story-`)
//line views/vworkspace/EstimateWorkspace.html:40
		qw422016.E().S(s.ID.String())
//line views/vworkspace/EstimateWorkspace.html:40
		qw422016.N().S(`">`)
//line views/vworkspace/EstimateWorkspace.html:40
		qw422016.E().S(s.TitleString())
//line views/vworkspace/EstimateWorkspace.html:40
		qw422016.N().S(`</a></td>
              <td class="shrink">0</td>
            </tr>
`)
//line views/vworkspace/EstimateWorkspace.html:43
	}
//line views/vworkspace/EstimateWorkspace.html:43
	qw422016.N().S(`          </tbody>
        </table>
`)
//line views/vworkspace/EstimateWorkspace.html:46
	for _, s := range w.Stories {
//line views/vworkspace/EstimateWorkspace.html:46
		qw422016.N().S(`        <div id="modal-story-`)
//line views/vworkspace/EstimateWorkspace.html:47
		qw422016.E().S(s.ID.String())
//line views/vworkspace/EstimateWorkspace.html:47
		qw422016.N().S(`" class="modal" style="display: none;">
          <a class="backdrop" href="#"></a>
          <div class="modal-content">
            <div class="modal-header">
              <a href="#" class="modal-close">×</a>
              <h2>`)
//line views/vworkspace/EstimateWorkspace.html:52
		qw422016.E().S(s.TitleString())
//line views/vworkspace/EstimateWorkspace.html:52
		qw422016.N().S(`</h2>
            </div>
            <div class="modal-body">
              TODO
            </div>
          </div>
        </div>
`)
//line views/vworkspace/EstimateWorkspace.html:59
	}
//line views/vworkspace/EstimateWorkspace.html:59
	qw422016.N().S(`      </div>
    </div>
    <div id="panel-self">
      <div class="card">
        <a href="#modal-self"><h3>`)
//line views/vworkspace/EstimateWorkspace.html:64
	components.StreamSVGRefIcon(qw422016, `profile`, ps)
//line views/vworkspace/EstimateWorkspace.html:64
	qw422016.E().S(self.Name)
//line views/vworkspace/EstimateWorkspace.html:64
	qw422016.N().S(`</h3></a>
        <em>`)
//line views/vworkspace/EstimateWorkspace.html:65
	qw422016.E().S(string(self.Role))
//line views/vworkspace/EstimateWorkspace.html:65
	qw422016.N().S(`</em>
      </div>
      `)
//line views/vworkspace/EstimateWorkspace.html:67
	StreamSelfModal(qw422016, self.Name, self.Picture, self.Role)
//line views/vworkspace/EstimateWorkspace.html:67
	qw422016.N().S(`
    </div>
    <div id="panel-members">
      <div class="card">
        <a href="#modal-invite"><h3>`)
//line views/vworkspace/EstimateWorkspace.html:71
	components.StreamSVGRefIcon(qw422016, `users`, ps)
//line views/vworkspace/EstimateWorkspace.html:71
	qw422016.N().S(`Members</h3></a>
        <table class="mt expanded">
          <tbody>
`)
//line views/vworkspace/EstimateWorkspace.html:74
	for _, m := range others {
//line views/vworkspace/EstimateWorkspace.html:74
		qw422016.N().S(`            `)
//line views/vworkspace/EstimateWorkspace.html:75
		StreamMemberRow(qw422016, m.UserID, m.Name, m.Picture, m.Role, m.Updated)
//line views/vworkspace/EstimateWorkspace.html:75
		qw422016.N().S(`
`)
//line views/vworkspace/EstimateWorkspace.html:76
	}
//line views/vworkspace/EstimateWorkspace.html:76
	qw422016.N().S(`          </tbody>
        </table>
`)
//line views/vworkspace/EstimateWorkspace.html:79
	for _, m := range others {
//line views/vworkspace/EstimateWorkspace.html:79
		qw422016.N().S(`        `)
//line views/vworkspace/EstimateWorkspace.html:80
		StreamMemberModal(qw422016, m.UserID, m.Name, m.Picture, m.Role, m.Updated)
//line views/vworkspace/EstimateWorkspace.html:80
		qw422016.N().S(`
`)
//line views/vworkspace/EstimateWorkspace.html:81
	}
//line views/vworkspace/EstimateWorkspace.html:81
	qw422016.N().S(`      </div>
    </div>
    `)
//line views/vworkspace/EstimateWorkspace.html:84
	StreamInviteModal(qw422016)
//line views/vworkspace/EstimateWorkspace.html:84
	qw422016.N().S(`
  </div>
  `)
//line views/vworkspace/EstimateWorkspace.html:86
	components.StreamJSONModal(qw422016, "estimate", "Estimate JSON", w, 1)
//line views/vworkspace/EstimateWorkspace.html:86
	qw422016.N().S(`
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const estimate = `)
//line views/vworkspace/EstimateWorkspace.html:89
	qw422016.N().S(util.ToJSONCompact(t))
//line views/vworkspace/EstimateWorkspace.html:89
	qw422016.N().S(`;
      const members = `)
//line views/vworkspace/EstimateWorkspace.html:90
	qw422016.N().S(util.ToJSONCompact(w.Members))
//line views/vworkspace/EstimateWorkspace.html:90
	qw422016.N().S(`;
      const permissions = `)
//line views/vworkspace/EstimateWorkspace.html:91
	qw422016.N().S(util.ToJSONCompact(w.Permissions))
//line views/vworkspace/EstimateWorkspace.html:91
	qw422016.N().S(`;
      rituals.initWorkspace("estimate", estimate, members, permissions);
    });
  </script>
`)
//line views/vworkspace/EstimateWorkspace.html:95
}

//line views/vworkspace/EstimateWorkspace.html:95
func (p *EstimateWorkspace) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/EstimateWorkspace.html:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/EstimateWorkspace.html:95
	p.StreamBody(qw422016, as, ps)
//line views/vworkspace/EstimateWorkspace.html:95
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/EstimateWorkspace.html:95
}

//line views/vworkspace/EstimateWorkspace.html:95
func (p *EstimateWorkspace) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkspace/EstimateWorkspace.html:95
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/EstimateWorkspace.html:95
	p.WriteBody(qb422016, as, ps)
//line views/vworkspace/EstimateWorkspace.html:95
	qs422016 := string(qb422016.B)
//line views/vworkspace/EstimateWorkspace.html:95
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/EstimateWorkspace.html:95
	return qs422016
//line views/vworkspace/EstimateWorkspace.html:95
}

//line views/vworkspace/EstimateWorkspace.html:97
func StreamEstimateWorkspaceModal(qw422016 *qt422016.Writer, w *workspace.FullEstimate) {
//line views/vworkspace/EstimateWorkspace.html:97
	qw422016.N().S(`
  <div id="modal-estimate-config" class="modal" style="display: none;">
    <a class="backdrop" href="#"></a>
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="modal-close">×</a>
        <h2>`)
//line views/vworkspace/EstimateWorkspace.html:103
	qw422016.E().S(w.Estimate.TitleString())
//line views/vworkspace/EstimateWorkspace.html:103
	qw422016.N().S(`</h2>
      </div>
      <div class="modal-body">
        TODO
      </div>
    </div>
  </div>
`)
//line views/vworkspace/EstimateWorkspace.html:110
}

//line views/vworkspace/EstimateWorkspace.html:110
func WriteEstimateWorkspaceModal(qq422016 qtio422016.Writer, w *workspace.FullEstimate) {
//line views/vworkspace/EstimateWorkspace.html:110
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/EstimateWorkspace.html:110
	StreamEstimateWorkspaceModal(qw422016, w)
//line views/vworkspace/EstimateWorkspace.html:110
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/EstimateWorkspace.html:110
}

//line views/vworkspace/EstimateWorkspace.html:110
func EstimateWorkspaceModal(w *workspace.FullEstimate) string {
//line views/vworkspace/EstimateWorkspace.html:110
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/EstimateWorkspace.html:110
	WriteEstimateWorkspaceModal(qb422016, w)
//line views/vworkspace/EstimateWorkspace.html:110
	qs422016 := string(qb422016.B)
//line views/vworkspace/EstimateWorkspace.html:110
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/EstimateWorkspace.html:110
	return qs422016
//line views/vworkspace/EstimateWorkspace.html:110
}
