
-- {% func ResetDatabase() %}
drop table if exists "feedback";
drop table if exists "retro_permission";
drop table if exists "retro_history";
drop table if exists "retro_member";
drop table if exists "retro";
drop table if exists "report";
drop table if exists "standup_permission";
drop table if exists "standup_history";
drop table if exists "standup_member";
drop table if exists "standup";
drop table if exists "vote";
drop table if exists "story";
drop table if exists "estimate_permission";
drop table if exists "estimate_history";
drop table if exists "estimate_member";
drop table if exists "estimate";
drop table if exists "sprint_permission";
drop table if exists "sprint_history";
drop table if exists "sprint_member";
drop table if exists "sprint";
drop table if exists "team_permission";
drop table if exists "team_history";
drop table if exists "team_member";
drop table if exists "team";
drop table if exists "email";
drop table if exists "action";
drop table if exists "comment";
drop table if exists "user";
drop table if exists "migration"
-- {% endfunc %}
