// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vstandup/Detail.html:2
package vstandup

//line views/vstandup/Detail.html:2
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/lib/filter"
	"github.com/kyleu/rituals/app/sprint"
	"github.com/kyleu/rituals/app/standup"
	"github.com/kyleu/rituals/app/standup/report"
	"github.com/kyleu/rituals/app/standup/uhistory"
	"github.com/kyleu/rituals/app/standup/umember"
	"github.com/kyleu/rituals/app/standup/upermission"
	"github.com/kyleu/rituals/app/team"
	"github.com/kyleu/rituals/app/user"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
	"github.com/kyleu/rituals/views/vstandup/vreport"
	"github.com/kyleu/rituals/views/vstandup/vuhistory"
	"github.com/kyleu/rituals/views/vstandup/vumember"
	"github.com/kyleu/rituals/views/vstandup/vupermission"
)

//line views/vstandup/Detail.html:22
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vstandup/Detail.html:22
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vstandup/Detail.html:22
type Detail struct {
	layout.Basic
	Model                         *standup.Standup
	Users                         user.Users
	Teams                         team.Teams
	Sprints                       sprint.Sprints
	Params                        filter.ParamSet
	ReportsByStandupID            report.Reports
	StandupHistoriesByStandupID   uhistory.StandupHistories
	StandupMembersByStandupID     umember.StandupMembers
	StandupPermissionsByStandupID upermission.StandupPermissions
}

//line views/vstandup/Detail.html:35
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/Detail.html:35
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-standup"><button type="button">JSON</button></a>
      <a href="`)
//line views/vstandup/Detail.html:39
	qw422016.E().S(p.Model.WebPath())
//line views/vstandup/Detail.html:39
	qw422016.N().S(`/edit"><button>`)
//line views/vstandup/Detail.html:39
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vstandup/Detail.html:39
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vstandup/Detail.html:41
	components.StreamSVGRefIcon(qw422016, `standup`, ps)
//line views/vstandup/Detail.html:41
	qw422016.N().S(` `)
//line views/vstandup/Detail.html:41
	qw422016.E().S(p.Model.TitleString())
//line views/vstandup/Detail.html:41
	qw422016.N().S(`</h3>
    <div><a href="/admin/db/standup"><em>Standup</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vstandup/Detail.html:47
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vstandup/Detail.html:47
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Slug</th>
          <td>`)
//line views/vstandup/Detail.html:51
	qw422016.E().S(p.Model.Slug)
//line views/vstandup/Detail.html:51
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Title</th>
          <td><strong>`)
//line views/vstandup/Detail.html:55
	qw422016.E().S(p.Model.Title)
//line views/vstandup/Detail.html:55
	qw422016.N().S(`</strong></td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Icon</th>
          <td>`)
//line views/vstandup/Detail.html:59
	qw422016.E().S(p.Model.Icon)
//line views/vstandup/Detail.html:59
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Available options: [new, active, complete, deleted]">Status</th>
          <td>`)
//line views/vstandup/Detail.html:63
	qw422016.E().V(p.Model.Status)
//line views/vstandup/Detail.html:63
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000) (optional)">Team ID</th>
          <td>
            <div class="icon">`)
//line views/vstandup/Detail.html:68
	components.StreamDisplayUUID(qw422016, p.Model.TeamID)
//line views/vstandup/Detail.html:68
	if p.Model.TeamID != nil {
//line views/vstandup/Detail.html:68
		if x := p.Teams.Get(*p.Model.TeamID); x != nil {
//line views/vstandup/Detail.html:68
			qw422016.N().S(` (`)
//line views/vstandup/Detail.html:68
			qw422016.E().S(x.TitleString())
//line views/vstandup/Detail.html:68
			qw422016.N().S(`)`)
//line views/vstandup/Detail.html:68
		}
//line views/vstandup/Detail.html:68
	}
//line views/vstandup/Detail.html:68
	qw422016.N().S(`</div>
            `)
//line views/vstandup/Detail.html:69
	if p.Model.TeamID != nil {
//line views/vstandup/Detail.html:69
		qw422016.N().S(`<a title="Team" href="`)
//line views/vstandup/Detail.html:69
		qw422016.E().S(`/team` + `/` + p.Model.TeamID.String())
//line views/vstandup/Detail.html:69
		qw422016.N().S(`">`)
//line views/vstandup/Detail.html:69
		components.StreamSVGRefIcon(qw422016, "team", ps)
//line views/vstandup/Detail.html:69
		qw422016.N().S(`</a>`)
//line views/vstandup/Detail.html:69
	}
//line views/vstandup/Detail.html:69
	qw422016.N().S(`
          </td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000) (optional)">Sprint ID</th>
          <td>
            <div class="icon">`)
//line views/vstandup/Detail.html:75
	components.StreamDisplayUUID(qw422016, p.Model.SprintID)
//line views/vstandup/Detail.html:75
	if p.Model.SprintID != nil {
//line views/vstandup/Detail.html:75
		if x := p.Sprints.Get(*p.Model.SprintID); x != nil {
//line views/vstandup/Detail.html:75
			qw422016.N().S(` (`)
//line views/vstandup/Detail.html:75
			qw422016.E().S(x.TitleString())
//line views/vstandup/Detail.html:75
			qw422016.N().S(`)`)
//line views/vstandup/Detail.html:75
		}
//line views/vstandup/Detail.html:75
	}
//line views/vstandup/Detail.html:75
	qw422016.N().S(`</div>
            `)
//line views/vstandup/Detail.html:76
	if p.Model.SprintID != nil {
//line views/vstandup/Detail.html:76
		qw422016.N().S(`<a title="Sprint" href="`)
//line views/vstandup/Detail.html:76
		qw422016.E().S(`/sprint` + `/` + p.Model.SprintID.String())
//line views/vstandup/Detail.html:76
		qw422016.N().S(`">`)
//line views/vstandup/Detail.html:76
		components.StreamSVGRefIcon(qw422016, "sprint", ps)
//line views/vstandup/Detail.html:76
		qw422016.N().S(`</a>`)
//line views/vstandup/Detail.html:76
	}
//line views/vstandup/Detail.html:76
	qw422016.N().S(`
          </td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Owner</th>
          <td>
            <div class="icon">`)
//line views/vstandup/Detail.html:82
	components.StreamDisplayUUID(qw422016, &p.Model.Owner)
//line views/vstandup/Detail.html:82
	if x := p.Users.Get(p.Model.Owner); x != nil {
//line views/vstandup/Detail.html:82
		qw422016.N().S(` (`)
//line views/vstandup/Detail.html:82
		qw422016.E().S(x.TitleString())
//line views/vstandup/Detail.html:82
		qw422016.N().S(`)`)
//line views/vstandup/Detail.html:82
	}
//line views/vstandup/Detail.html:82
	qw422016.N().S(`</div>
            <a title="User" href="`)
//line views/vstandup/Detail.html:83
	qw422016.E().S(`/user` + `/` + p.Model.Owner.String())
//line views/vstandup/Detail.html:83
	qw422016.N().S(`">`)
//line views/vstandup/Detail.html:83
	components.StreamSVGRefIcon(qw422016, "profile", ps)
//line views/vstandup/Detail.html:83
	qw422016.N().S(`</a>
          </td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vstandup/Detail.html:88
	components.StreamDisplayTimestamp(qw422016, &p.Model.Created)
//line views/vstandup/Detail.html:88
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Updated</th>
          <td>`)
//line views/vstandup/Detail.html:92
	components.StreamDisplayTimestamp(qw422016, p.Model.Updated)
//line views/vstandup/Detail.html:92
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vstandup/Detail.html:99
	if len(p.ReportsByStandupID) > 0 {
//line views/vstandup/Detail.html:99
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vstandup/Detail.html:101
		components.StreamSVGRefIcon(qw422016, `file-alt`, ps)
//line views/vstandup/Detail.html:101
		qw422016.N().S(` Related reports by [standup id]</h3>
    <div class="overflow clear">
      `)
//line views/vstandup/Detail.html:103
		vreport.StreamTable(qw422016, p.ReportsByStandupID, nil, nil, p.Params, as, ps)
//line views/vstandup/Detail.html:103
		qw422016.N().S(`
    </div>
  </div>
`)
//line views/vstandup/Detail.html:106
	}
//line views/vstandup/Detail.html:107
	if len(p.StandupHistoriesByStandupID) > 0 {
//line views/vstandup/Detail.html:107
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vstandup/Detail.html:109
		components.StreamSVGRefIcon(qw422016, `history`, ps)
//line views/vstandup/Detail.html:109
		qw422016.N().S(` Related histories by [standup id]</h3>
    <div class="overflow clear">
      `)
//line views/vstandup/Detail.html:111
		vuhistory.StreamTable(qw422016, p.StandupHistoriesByStandupID, nil, p.Params, as, ps)
//line views/vstandup/Detail.html:111
		qw422016.N().S(`
    </div>
  </div>
`)
//line views/vstandup/Detail.html:114
	}
//line views/vstandup/Detail.html:115
	if len(p.StandupMembersByStandupID) > 0 {
//line views/vstandup/Detail.html:115
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vstandup/Detail.html:117
		components.StreamSVGRefIcon(qw422016, `users`, ps)
//line views/vstandup/Detail.html:117
		qw422016.N().S(` Related members by [standup id]</h3>
    <div class="overflow clear">
      `)
//line views/vstandup/Detail.html:119
		vumember.StreamTable(qw422016, p.StandupMembersByStandupID, nil, nil, p.Params, as, ps)
//line views/vstandup/Detail.html:119
		qw422016.N().S(`
    </div>
  </div>
`)
//line views/vstandup/Detail.html:122
	}
//line views/vstandup/Detail.html:123
	if len(p.StandupPermissionsByStandupID) > 0 {
//line views/vstandup/Detail.html:123
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vstandup/Detail.html:125
		components.StreamSVGRefIcon(qw422016, `permission`, ps)
//line views/vstandup/Detail.html:125
		qw422016.N().S(` Related permissions by [standup id]</h3>
    <div class="overflow clear">
      `)
//line views/vstandup/Detail.html:127
		vupermission.StreamTable(qw422016, p.StandupPermissionsByStandupID, nil, p.Params, as, ps)
//line views/vstandup/Detail.html:127
		qw422016.N().S(`
    </div>
  </div>
`)
//line views/vstandup/Detail.html:130
	}
//line views/vstandup/Detail.html:130
	qw422016.N().S(`  `)
//line views/vstandup/Detail.html:131
	components.StreamJSONModal(qw422016, "standup", "Standup JSON", p.Model, 1)
//line views/vstandup/Detail.html:131
	qw422016.N().S(`
`)
//line views/vstandup/Detail.html:132
}

//line views/vstandup/Detail.html:132
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vstandup/Detail.html:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vstandup/Detail.html:132
	p.StreamBody(qw422016, as, ps)
//line views/vstandup/Detail.html:132
	qt422016.ReleaseWriter(qw422016)
//line views/vstandup/Detail.html:132
}

//line views/vstandup/Detail.html:132
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vstandup/Detail.html:132
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vstandup/Detail.html:132
	p.WriteBody(qb422016, as, ps)
//line views/vstandup/Detail.html:132
	qs422016 := string(qb422016.B)
//line views/vstandup/Detail.html:132
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vstandup/Detail.html:132
	return qs422016
//line views/vstandup/Detail.html:132
}
