// Code generated by qtc from "RetroWorkspace.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkspace/vwretro/RetroWorkspace.html:1
package vwretro

//line views/vworkspace/vwretro/RetroWorkspace.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/action"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/enum"
	"github.com/kyleu/rituals/app/retro"
	"github.com/kyleu/rituals/app/sprint"
	"github.com/kyleu/rituals/app/team"
	"github.com/kyleu/rituals/app/util"
	"github.com/kyleu/rituals/app/workspace"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
	"github.com/kyleu/rituals/views/vworkspace/vwutil"
)

//line views/vworkspace/vwretro/RetroWorkspace.html:16
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkspace/vwretro/RetroWorkspace.html:16
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkspace/vwretro/RetroWorkspace.html:16
type RetroWorkspace struct {
	layout.Basic
	FullRetro *workspace.FullRetro
	Teams     team.Teams
	Sprints   sprint.Sprints
}

//line views/vworkspace/vwretro/RetroWorkspace.html:23
func (p *RetroWorkspace) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/vwretro/RetroWorkspace.html:23
	qw422016.N().S(`
`)
//line views/vworkspace/vwretro/RetroWorkspace.html:25
	w := p.FullRetro
	r := w.Retro

//line views/vworkspace/vwretro/RetroWorkspace.html:27
	qw422016.N().S(`  <div class="flex-wrap">
    <div id="panel-summary">
      <div class="card">
        <div class="right">
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:32
	vwutil.StreamPermissionsLink(qw422016, enum.ModelServiceRetro, r.ID, w.Permissions.ToPermissions(), ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:32
	qw422016.N().S(`
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:33
	vwutil.StreamComments(qw422016, enum.ModelServiceRetro, r.ID, r.TitleString(), w.Comments, w.UtilMembers, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:33
	qw422016.N().S(`
        </div>
        <a href="#modal-retro-config" id="modal-retro-config-link"><h3>
          <span id="model-icon">`)
//line views/vworkspace/vwretro/RetroWorkspace.html:36
	components.StreamSVGRefIcon(qw422016, r.IconSafe(), ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:36
	qw422016.N().S(`</span>
          <span id="model-title">`)
//line views/vworkspace/vwretro/RetroWorkspace.html:37
	qw422016.E().S(r.TitleString())
//line views/vworkspace/vwretro/RetroWorkspace.html:37
	qw422016.N().S(`</span>
        </h3></a>
        `)
//line views/vworkspace/vwretro/RetroWorkspace.html:39
	vwutil.StreamBanner(qw422016, w.Team, w.Sprint, "retrospective")
//line views/vworkspace/vwretro/RetroWorkspace.html:39
	qw422016.N().S(`
        <span id="owner-id" style="display: none;">`)
//line views/vworkspace/vwretro/RetroWorkspace.html:40
	qw422016.E().S(r.Owner.String())
//line views/vworkspace/vwretro/RetroWorkspace.html:40
	qw422016.N().S(`</span>
        `)
//line views/vworkspace/vwretro/RetroWorkspace.html:41
	StreamRetroWorkspaceModal(qw422016, r, p.Teams, p.Sprints, w.Permissions.ToPermissions(), ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:41
	qw422016.N().S(`
      </div>
    </div>
    <div id="panel-detail">
      <div class="card">
        <h3>`)
//line views/vworkspace/vwretro/RetroWorkspace.html:46
	components.StreamSVGRefIcon(qw422016, `comment`, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:46
	qw422016.N().S(`Feedback</h3>
        <div class="clear"></div>
        `)
//line views/vworkspace/vwretro/RetroWorkspace.html:48
	StreamRetroWorkspaceFeedbacks(qw422016, ps.Profile.ID, ps.Username(), w, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:48
	qw422016.N().S(`
      </div>
    </div>
    `)
//line views/vworkspace/vwretro/RetroWorkspace.html:51
	vwutil.StreamMemberPanels(qw422016, w.UtilMembers, w.Admin(), r.PublicWebPath(), ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:51
	qw422016.N().S(`
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      initWorkspace("`)
//line views/vworkspace/vwretro/RetroWorkspace.html:55
	qw422016.E().S(util.KeyRetro)
//line views/vworkspace/vwretro/RetroWorkspace.html:55
	qw422016.N().S(`", "`)
//line views/vworkspace/vwretro/RetroWorkspace.html:55
	qw422016.E().S(r.ID.String())
//line views/vworkspace/vwretro/RetroWorkspace.html:55
	qw422016.N().S(`");
    });
  </script>
`)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
}

//line views/vworkspace/vwretro/RetroWorkspace.html:58
func (p *RetroWorkspace) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	p.StreamBody(qw422016, as, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
}

//line views/vworkspace/vwretro/RetroWorkspace.html:58
func (p *RetroWorkspace) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	p.WriteBody(qb422016, as, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	qs422016 := string(qb422016.B)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:58
	return qs422016
//line views/vworkspace/vwretro/RetroWorkspace.html:58
}

//line views/vworkspace/vwretro/RetroWorkspace.html:60
func StreamRetroWorkspaceModal(qw422016 *qt422016.Writer, r *retro.Retro, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) {
//line views/vworkspace/vwretro/RetroWorkspace.html:60
	qw422016.N().S(`
  <div id="modal-retro-config" class="modal" style="display: none;">
    <a class="backdrop" href="#"></a>
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="modal-close">×</a>
        <h2>Retro</h2>
      </div>
      <div class="modal-body">
        <form action="`)
//line views/vworkspace/vwretro/RetroWorkspace.html:69
	qw422016.E().S(r.PublicWebPath())
//line views/vworkspace/vwretro/RetroWorkspace.html:69
	qw422016.N().S(`" method="post" class="expanded">
          <input type="hidden" name="action" value="`)
//line views/vworkspace/vwretro/RetroWorkspace.html:70
	qw422016.E().S(string(action.ActUpdate))
//line views/vworkspace/vwretro/RetroWorkspace.html:70
	qw422016.N().S(`" />
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:71
	components.StreamFormVerticalInput(qw422016, "title", "", "Title", r.TitleString(), 5, "The name of your retro")
//line views/vworkspace/vwretro/RetroWorkspace.html:71
	qw422016.N().S(`
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:72
	components.StreamFormVerticalIconPicker(qw422016, "icon", "Icon", r.IconSafe(), ps, 5)
//line views/vworkspace/vwretro/RetroWorkspace.html:72
	qw422016.N().S(`
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:73
	components.StreamFormVerticalInputTags(qw422016, "categories", "", "Categories", r.Categories, ps, 5, "The available categories for this retro")
//line views/vworkspace/vwretro/RetroWorkspace.html:73
	qw422016.N().S(`
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:74
	components.StreamFormVerticalSelect(qw422016, util.KeyTeam, "config-team-input", "Team", util.UUIDString(r.TeamID), teams.IDStrings(true), teams.TitleStrings("- no team -"), 5)
//line views/vworkspace/vwretro/RetroWorkspace.html:74
	qw422016.N().S(`
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:75
	components.StreamFormVerticalSelect(qw422016, util.KeySprint, "config-sprint-input", "Sprint", util.UUIDString(r.SprintID), sprints.IDStrings(true), sprints.TitleStrings("- no sprint -"), 5)
//line views/vworkspace/vwretro/RetroWorkspace.html:75
	qw422016.N().S(`
          <hr />
          `)
//line views/vworkspace/vwretro/RetroWorkspace.html:77
	vwutil.StreamPermissionsForm(qw422016, util.KeyRetro, perms, true, teams, true, sprints, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:77
	qw422016.N().S(`
          <hr />
          <div class="right"><button type="submit">Save</button></div>
          <div class="clear"></div>
        </form>
      </div>
    </div>
  </div>
`)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
}

//line views/vworkspace/vwretro/RetroWorkspace.html:85
func WriteRetroWorkspaceModal(qq422016 qtio422016.Writer, r *retro.Retro, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) {
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	StreamRetroWorkspaceModal(qw422016, r, teams, sprints, perms, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	qt422016.ReleaseWriter(qw422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
}

//line views/vworkspace/vwretro/RetroWorkspace.html:85
func RetroWorkspaceModal(r *retro.Retro, teams team.Teams, sprints sprint.Sprints, perms util.Permissions, ps *cutil.PageState) string {
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	WriteRetroWorkspaceModal(qb422016, r, teams, sprints, perms, ps)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	qs422016 := string(qb422016.B)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkspace/vwretro/RetroWorkspace.html:85
	return qs422016
//line views/vworkspace/vwretro/RetroWorkspace.html:85
}
