// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vestimate/vstory/Detail.html:1
package vstory

//line views/vestimate/vstory/Detail.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/enum"
	"github.com/kyleu/rituals/app/estimate"
	"github.com/kyleu/rituals/app/estimate/story"
	"github.com/kyleu/rituals/app/estimate/story/vote"
	"github.com/kyleu/rituals/app/lib/filter"
	"github.com/kyleu/rituals/app/user"
	"github.com/kyleu/rituals/app/util"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/components/view"
	"github.com/kyleu/rituals/views/layout"
	"github.com/kyleu/rituals/views/vestimate/vstory/vvote"
)

//line views/vestimate/vstory/Detail.html:17
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vestimate/vstory/Detail.html:17
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vestimate/vstory/Detail.html:17
type Detail struct {
	layout.Basic
	Model                *story.Story
	EstimateByEstimateID *estimate.Estimate
	UserByUserID         *user.User
	Params               filter.ParamSet
	RelVotesByStoryID    vote.Votes
}

//line views/vestimate/vstory/Detail.html:26
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vestimate/vstory/Detail.html:26
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-story"><button type="button">`)
//line views/vestimate/vstory/Detail.html:29
	components.StreamSVGButton(qw422016, "file", ps)
//line views/vestimate/vstory/Detail.html:29
	qw422016.N().S(` JSON</button></a>
      <a href="`)
//line views/vestimate/vstory/Detail.html:30
	qw422016.E().S(p.Model.WebPath())
//line views/vestimate/vstory/Detail.html:30
	qw422016.N().S(`/edit"><button>`)
//line views/vestimate/vstory/Detail.html:30
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vestimate/vstory/Detail.html:30
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vestimate/vstory/Detail.html:32
	components.StreamSVGIcon(qw422016, `story`, ps)
//line views/vestimate/vstory/Detail.html:32
	qw422016.N().S(` `)
//line views/vestimate/vstory/Detail.html:32
	qw422016.E().S(p.Model.TitleString())
//line views/vestimate/vstory/Detail.html:32
	qw422016.N().S(`</h3>
    <div><a href="/admin/db/estimate/story"><em>Story</em></a></div>
    <div class="mt overflow full-width">
      <table>
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:39
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vestimate/vstory/Detail.html:39
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Estimate ID</th>
            <td class="nowrap">
              `)
//line views/vestimate/vstory/Detail.html:44
	view.StreamUUID(qw422016, &p.Model.EstimateID)
//line views/vestimate/vstory/Detail.html:44
	if p.EstimateByEstimateID != nil {
//line views/vestimate/vstory/Detail.html:44
		qw422016.N().S(` (`)
//line views/vestimate/vstory/Detail.html:44
		qw422016.E().S(p.EstimateByEstimateID.TitleString())
//line views/vestimate/vstory/Detail.html:44
		qw422016.N().S(`)`)
//line views/vestimate/vstory/Detail.html:44
	}
//line views/vestimate/vstory/Detail.html:44
	qw422016.N().S(`
              <a title="Estimate" href="`)
//line views/vestimate/vstory/Detail.html:45
	qw422016.E().S(`/admin/db/estimate` + `/` + p.Model.EstimateID.String())
//line views/vestimate/vstory/Detail.html:45
	qw422016.N().S(`">`)
//line views/vestimate/vstory/Detail.html:45
	components.StreamSVGLink(qw422016, `estimate`, ps)
//line views/vestimate/vstory/Detail.html:45
	qw422016.N().S(`</a>
            </td>
          </tr>
          <tr>
            <th class="shrink" title="Integer">Idx</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:50
	qw422016.N().D(p.Model.Idx)
//line views/vestimate/vstory/Detail.html:50
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">User ID</th>
            <td class="nowrap">
              `)
//line views/vestimate/vstory/Detail.html:55
	view.StreamUUID(qw422016, &p.Model.UserID)
//line views/vestimate/vstory/Detail.html:55
	if p.UserByUserID != nil {
//line views/vestimate/vstory/Detail.html:55
		qw422016.N().S(` (`)
//line views/vestimate/vstory/Detail.html:55
		qw422016.E().S(p.UserByUserID.TitleString())
//line views/vestimate/vstory/Detail.html:55
		qw422016.N().S(`)`)
//line views/vestimate/vstory/Detail.html:55
	}
//line views/vestimate/vstory/Detail.html:55
	qw422016.N().S(`
              <a title="User" href="`)
//line views/vestimate/vstory/Detail.html:56
	qw422016.E().S(`/admin/db/user` + `/` + p.Model.UserID.String())
//line views/vestimate/vstory/Detail.html:56
	qw422016.N().S(`">`)
//line views/vestimate/vstory/Detail.html:56
	components.StreamSVGLink(qw422016, `profile`, ps)
//line views/vestimate/vstory/Detail.html:56
	qw422016.N().S(`</a>
            </td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Title</th>
            <td><strong>`)
//line views/vestimate/vstory/Detail.html:61
	view.StreamString(qw422016, p.Model.Title)
//line views/vestimate/vstory/Detail.html:61
	qw422016.N().S(`</strong></td>
          </tr>
          <tr>
            <th class="shrink" title="`)
//line views/vestimate/vstory/Detail.html:64
	qw422016.E().S(enum.AllSessionStatuses.Help())
//line views/vestimate/vstory/Detail.html:64
	qw422016.N().S(`">Status</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:65
	qw422016.E().S(p.Model.Status.String())
//line views/vestimate/vstory/Detail.html:65
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Final Vote</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:69
	view.StreamString(qw422016, p.Model.FinalVote)
//line views/vestimate/vstory/Detail.html:69
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Date and time, in almost any format">Created</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:73
	view.StreamTimestamp(qw422016, &p.Model.Created)
//line views/vestimate/vstory/Detail.html:73
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Date and time, in almost any format (optional)">Updated</th>
            <td>`)
//line views/vestimate/vstory/Detail.html:77
	view.StreamTimestamp(qw422016, p.Model.Updated)
//line views/vestimate/vstory/Detail.html:77
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vestimate/vstory/Detail.html:85
	relationHelper := story.Stories{p.Model}

//line views/vestimate/vstory/Detail.html:85
	qw422016.N().S(`  <div class="card">
    <h3 class="mb">Relations</h3>
    <ul class="accordion">
      <li>
        <input id="accordion-VotesByStoryID" type="checkbox" hidden="hidden"`)
//line views/vestimate/vstory/Detail.html:90
	if p.Params.Specifies(`vote`) {
//line views/vestimate/vstory/Detail.html:90
		qw422016.N().S(` checked="checked"`)
//line views/vestimate/vstory/Detail.html:90
	}
//line views/vestimate/vstory/Detail.html:90
	qw422016.N().S(` />
        <label for="accordion-VotesByStoryID">
          `)
//line views/vestimate/vstory/Detail.html:92
	components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vestimate/vstory/Detail.html:92
	qw422016.N().S(`
          `)
//line views/vestimate/vstory/Detail.html:93
	components.StreamSVGInline(qw422016, `vote-yea`, 16, ps)
//line views/vestimate/vstory/Detail.html:93
	qw422016.N().S(`
          `)
//line views/vestimate/vstory/Detail.html:94
	qw422016.E().S(util.StringPlural(len(p.RelVotesByStoryID), "Vote"))
//line views/vestimate/vstory/Detail.html:94
	qw422016.N().S(` by [Story ID]
        </label>
        <div class="bd"><div><div>
`)
//line views/vestimate/vstory/Detail.html:97
	if len(p.RelVotesByStoryID) == 0 {
//line views/vestimate/vstory/Detail.html:97
		qw422016.N().S(`          <em>no related Votes</em>
`)
//line views/vestimate/vstory/Detail.html:99
	} else {
//line views/vestimate/vstory/Detail.html:99
		qw422016.N().S(`          <div class="overflow clear">
            `)
//line views/vestimate/vstory/Detail.html:101
		vvote.StreamTable(qw422016, p.RelVotesByStoryID, relationHelper, nil, p.Params, as, ps)
//line views/vestimate/vstory/Detail.html:101
		qw422016.N().S(`
          </div>
`)
//line views/vestimate/vstory/Detail.html:103
	}
//line views/vestimate/vstory/Detail.html:103
	qw422016.N().S(`        </div></div></div>
      </li>
    </ul>
  </div>
  `)
//line views/vestimate/vstory/Detail.html:108
	components.StreamJSONModal(qw422016, "story", "Story JSON", p.Model, 1)
//line views/vestimate/vstory/Detail.html:108
	qw422016.N().S(`
`)
//line views/vestimate/vstory/Detail.html:109
}

//line views/vestimate/vstory/Detail.html:109
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vestimate/vstory/Detail.html:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vestimate/vstory/Detail.html:109
	p.StreamBody(qw422016, as, ps)
//line views/vestimate/vstory/Detail.html:109
	qt422016.ReleaseWriter(qw422016)
//line views/vestimate/vstory/Detail.html:109
}

//line views/vestimate/vstory/Detail.html:109
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vestimate/vstory/Detail.html:109
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vestimate/vstory/Detail.html:109
	p.WriteBody(qb422016, as, ps)
//line views/vestimate/vstory/Detail.html:109
	qs422016 := string(qb422016.B)
//line views/vestimate/vstory/Detail.html:109
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vestimate/vstory/Detail.html:109
	return qs422016
//line views/vestimate/vstory/Detail.html:109
}
