// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vtheme/List.html:1
package vtheme

//line views/vtheme/List.html:1
import (
	"github.com/kyleu/rituals/app"
	"github.com/kyleu/rituals/app/controller/cutil"
	"github.com/kyleu/rituals/app/lib/theme"
	"github.com/kyleu/rituals/views/components"
	"github.com/kyleu/rituals/views/layout"
)

//line views/vtheme/List.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtheme/List.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtheme/List.html:9
type List struct {
	layout.Basic
	Themes theme.Themes
}

//line views/vtheme/List.html:14
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtheme/List.html:14
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vtheme/List.html:16
	components.StreamSVGIcon(qw422016, `eye`, ps)
//line views/vtheme/List.html:16
	qw422016.N().S(` Add Theme</h3>
    <div class="mt">
      <a href="/theme/new" title="add new theme"><button>New Theme</button></a>
    </div>
  </div>
  <div class="card">
    <h3>`)
//line views/vtheme/List.html:22
	components.StreamSVGIcon(qw422016, `play`, ps)
//line views/vtheme/List.html:22
	qw422016.N().S(` Current Themes</h3>
    <div class="overflow full-width">
      <div class="theme-container mt">
`)
//line views/vtheme/List.html:25
	for _, t := range p.Themes {
//line views/vtheme/List.html:25
		qw422016.N().S(`        <div class="theme-item">
          <a href="/theme/`)
//line views/vtheme/List.html:27
		qw422016.N().U(t.Key)
//line views/vtheme/List.html:27
		qw422016.N().S(`">
            `)
//line views/vtheme/List.html:28
		StreamMockupTheme(qw422016, t, true, "app", 5, ps)
//line views/vtheme/List.html:28
		qw422016.N().S(`
          </a>
        </div>
`)
//line views/vtheme/List.html:31
	}
//line views/vtheme/List.html:31
	qw422016.N().S(`      </div>
    </div>
  </div>
`)
//line views/vtheme/List.html:35
}

//line views/vtheme/List.html:35
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtheme/List.html:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtheme/List.html:35
	p.StreamBody(qw422016, as, ps)
//line views/vtheme/List.html:35
	qt422016.ReleaseWriter(qw422016)
//line views/vtheme/List.html:35
}

//line views/vtheme/List.html:35
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtheme/List.html:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtheme/List.html:35
	p.WriteBody(qb422016, as, ps)
//line views/vtheme/List.html:35
	qs422016 := string(qb422016.B)
//line views/vtheme/List.html:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtheme/List.html:35
	return qs422016
//line views/vtheme/List.html:35
}
